apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-ui
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ui
data:
  idd4.yml: |-
    urls:
      hydra_login_url: https://{{ .Values.config.hostname }}/flow/login
      welcome_url: https://{{ .Values.config.hostname }}/
      settings_url: https://{{ .Values.config.hostname }}/self-service/settings/browser
      login_url: https://{{ .Values.config.hostname }}/self-service/login/browser
      invite_url: https://{{ .Values.config.hostname }}/invite
      registration_url_internal: http://{{ include "common.names.fullname" . }}-kratos-public/self-service/registration
      registration_url: https://{{ .Values.config.hostname }}/self-service/registration/browser
    hydra:
      admin_api_url: http://{{ include "common.names.fullname" . }}-hydra-admin
    kratos:
      admin_api_url: http://{{ include "common.names.fullname" . }}-kratos-admin
      public_api_url: http://{{ include "common.names.fullname" . }}-kratos-public
    keto:
      write_api_url: http://{{ include "common.names.fullname" . }}-keto-write
      read_api_url: http://{{ include "common.names.fullname" . }}-keto-read
    server:
      run_mode: debug
      endpoint: :4455