apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-ui
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http