apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-kratos
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kratos
type: Opaque
stringData:
  secretsDefault: {{ default .Values.config.kratos.secrets.default (randAlphaNum 32) | quote }}
  secretsCookie: {{ default .Values.config.kratos.secrets.cookie (randAlphaNum 32) | quote }}
  secretsCipher: {{ default .Values.config.kratos.secrets.cipher (randAlphaNum 32) | quote }}