apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-hydra-public
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: hydra
spec:
  type: ClusterIP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: hydra
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-public
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-hydra-admin
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: hydra
spec:
  type: ClusterIP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: hydra
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-admin