serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: https://localhost:4000/hydra/
  consent: https://localhost:4000/consent
  login: https://localhost:4000/flow/login
  logout: https://localhost:4000/flow/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
