version: v0.7.1-alpha.1

dsn: memory

serve:
  public:
    base_url: https://localhost:4000/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: https://localhost:4000/
  allowed_return_urls:
    - https://localhost:4000/

  methods:
    password:
      enabled: true
    totp:
      enabled: true
    webauthn:
      enabled: true
      config:
        rp:
          id: localhost
          display_name: Ory Foundation
          icon: http://www.ory.sh/an-icon.png
          origin: https://localhost:4000/login
        passwordless: true

  flows:
    error:
      ui_url: https://localhost:4000/error

    settings:
      ui_url: https://localhost:4000/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: false

    verification:
      enabled: false

    logout:
      after:
        default_browser_return_url: https://localhost:4000/login

    login:
      ui_url: https://localhost:4000/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://localhost:4000/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: "smtps://test:test@mailslurper:1025/?skip_ssl_verify=true"
